### ISSUE TITLE
compilation fails on message.go: not enough arguments in call to uuid.

### ISSUE THREAD

**Issue by robintiwari** [gocelery/gocelery#126]
I got following error when trying to compile the go project referencing gocelery:

github.com/gocelery/gocelery/message.go:XX:XX: not enough arguments in call to uuid.Must
	have (uuid.UUID)
	want (uuid.UUID, error)

if you look into the latest code for https://github.com/satori/go.uuid uuid.Must function has extra argument "error"

```
func Must(u UUID, err error) UUID {
	if err != nil {
		panic(err)
	}
	return u
}
```

**Comment by sickyoon** [comment]
This has been fixed a while ago: https://github.com/gocelery/gocelery/commit/1d9c08eaef92472494ab8d2d54c15040cbab6541
Please pull latest master.

**Comment by sickyoon** [comment]
You might still get this error if you use version < 1.2.0. Please use latest master branch.

**Comment by pbnsilva** [comment]
This is still an issue, or not?

`Must` expects `(uuid.UUID, error)`, see https://github.com/satori/go.uuid/blob/master/uuid.go#L156

**Comment by khoivun** [comment]
The latest mater branch now throws the same error in message.go instead
`../../../../pkg/mod/github.com/gocelery/gocelery@v0.0.0-20191008025616-26dc580ba02e/message.go:30:41: not enough arguments in call to uuid.Must
        have (uuid.UUID)
        want (uuid.UUID, error)
../../../../pkg/mod/github.com/gocelery/gocelery@v0.0.0-20191008025616-26dc580ba02e/message.go:31:35: not enough arguments in call to uuid.Must
        have (uuid.UUID)
        want (uuid.UUID, error)
../../../../pkg/mod/github.com/gocelery/gocelery@v0.0.0-20191008025616-26dc580ba02e/message.go:32:39: not enough arguments in call to uuid.Must
        have (uuid.UUID)
        want (uuid.UUID, error)
../../../../pkg/mod/github.com/gocelery/gocelery@v0.0.0-20191008025616-26dc580ba02e/message.go:43:29: not enough arguments in call to uuid.Must
        have (uuid.UUID)
        want (uuid.UUID, error)
../../../../pkg/mod/github.com/gocelery/gocelery@v0.0.0-20191008025616-26dc580ba02e/message.go:44:29: not enough arguments in call to uuid.Must
        have (uuid.UUID)
        want (uuid.UUID, error)
../../../../pkg/mod/github.com/gocelery/gocelery@v0.0.0-20191008025616-26dc580ba02e/message.go:51:28: not enough arguments in call to uuid.Must
        have (uuid.UUID)
        want (uuid.UUID, error)
../../../../pkg/mod/github.com/gocelery/gocelery@v0.0.0-20191008025616-26dc580ba02e/message.go:123:19: not enough arguments in call to uuid.Must
        have (uuid.UUID)
        want (uuid.UUID, error)
../../../../pkg/mod/github.com/gocelery/gocelery@v0.0.0-20191008025616-26dc580ba02e/message.go:133:22: not enough arguments in call to uuid.Must
        have (uuid.UUID)
        want (uuid.UUID, error)
`

**Comment by pbnsilva** [comment]
Update `go.uuid`: `go get github.com/satori/go.uuid@master`
